### ISSUE TITLE
"Roll for mod" rolls past the mods

### ISSUE THREAD

**Issue by ThirteenEra** [Mtb-3/Weightless#1]
Unzip program, make sure POE is in windowed fullscreen. Launch program.

Put a necklace into currency tab of stash. Type "skill gems" into search bar. Press "roll for mod", right click alteration orb, mouse over the necklace.

It keeps rolling until it hits the +1 to [some] skill gems, the frame around item lights up. But the program keeps on rolling and doesnt stop.

Same behavior appears for ANY mod - for example, typing "lightning damage" into search bar had it roll into mod and then kept on rolling.

Testing done on standard, remove-only tabs hidden.

EDIT: Did another test on Sanctum SC Trade. Put a pair of boots into currency tab, typed "movement" in search bar, selected alteration orbs, pressed "roll for mod". It kept rolling even after successfully rolling a movement mod.

Playing on 4k (3840x2160) monitor if that helps.

**Comment by Mtb-3** [comment]
Yeah, I forgot to mention that it might not work for ultra wide resolution monitors. I coded it based on standard 1920x1080 resolution. The post was removed since it's against ToS apparently.

**Comment by ThirteenEra** [comment]
3840x2160 is not ultrawide. its a standard 16:9.

**Comment by ThirteenEra** [comment]
Any chance you could add an override/option for people on 4k or 1440p? I love this program but i cant constantly swap my game to 1080p and back when i want to use it :/

Happy to test it for you if needed.

**Comment by Mtb-3** [comment]
Would you be able to test it if I gave you just the updated .py file or would you need an .exe? Going to test some things now.

**Comment by ThirteenEra** [comment]
Im technically savvy, but i dont code, so I don't know how to compile stuff. if you tell me what to do with the py file, sure.

**Comment by Mtb-3** [comment]
No worries. I just added a new build with the new resolutions for testing. Let me know if that works for you. Thanks

**Comment by ThirteenEra** [comment]
Sure. Downloading to test now

**Comment by ThirteenEra** [comment]
Doesnt seem to work, sadly.

Im using "modroller_16_9_testing.exe", but it has same issue - it rolls past the mods, even when item is highlighted.

**Comment by ThirteenEra** [comment]
https://user-images.githubusercontent.com/111650549/227952964-3e625482-3c8a-4a21-b8c6-c649578cf7e5.mp4

**Comment by Mtb-3** [comment]
Damn.. I think its because the screenshot area is too big to check for the pixel change before it rolls over. I need to make it more 
specific for your resolution. I have another idea.

**Comment by Mtb-3** [comment]
Just uploaded a new test. Let me know. Thanks

**Comment by ThirteenEra** [comment]
it WORKS!

It correctly stopped on boots with movement filtered, both times i tested. And then correctly stopped on amulet with "skill gems" filtered.

This is amazing! <3

EDIT: Socket/fusing is still broken though. It seems to roll once or twice adn then stops.
EDIT2: Nvm, now socket/fusing works. Must have been a hitch.

EDIT3: Can confirm both functions to work correctly!

**Comment by Mtb-3** [comment]
Ayy very nice to hear. Thanks for testing it out. Glad you like it and happy crafting for 3.21!

**Comment by ThirteenEra** [comment]
This will save me SO MUCH pain...

During sanctum it took me over 2.5k alts to roll +1 all... It was pain.

**Comment by ThirteenEra** [comment]
Just wanted to say - Thank you so much for this.

I know you werent welcomed on reddit due to "breaking tos", but i dont fucking care, my wrist health is more important to me than TOS. And your program already saved me so much pain this league. Thank you!

**Comment by Mtb-3** [comment]
I appreciate the message! I am glad that you are getting good use out of it.  Unfortunately I don't think GGG will prioritize health over "feeling the weight" anytime soon. I have an idea for something else for next league....maybe.
